name: Split Test

on:
    push:
        branches:
            - main
        tags:
            - '*'
    pull_request: ~

jobs:
    split_without_tag:
        runs-on: ubuntu-latest
        name: Split (Without Tag)
        if: "!startsWith(github.ref, 'refs/tags/')"

        steps:
            -
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -
                name: Split (Without Tag)
                uses: "./"
                with:
                    package_path: 'tests/packages/dummy'
                    ssh_private_key: ${{ secrets.SPLIT_SSH_PRIVATE_KEY }}
                    git_username: 'jakubtobiasz'
                    git_email: 'jakub.tobiasz@icloud.com'
                    repository_owner: 'jakubtobiasz'
                    repository_name: 'monoplus-split-dummy'

            -
                if: "startsWith(github.ref, 'refs/tags/')"
                name: Extract tag
                id: extract_tag
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

    split_with_tag:
        runs-on: ubuntu-latest
        name: Split (With Tag)
        if: "startsWith(github.ref, 'refs/tags/')"

        steps:
            -
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -
                name: Extract tag
                id: extract_tag
                run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}

            -
                name: Split (With Tag)
                uses: "./"
                with:
                    package_path: 'tests/packages/dummy'
                    ssh_private_key: ${{ secrets.SPLIT_SSH_PRIVATE_KEY }}
                    git_username: 'jakubtobiasz'
                    git_email: 'jakub.tobiasz@icloud.com'
                    repository_owner: 'jakubtobiasz'
                    repository_name: 'monoplus-split-dummy'
                    tag: ${{ steps.extract_tag.outputs.VERSION }}
