name: Split Test

on:
    push:
        branches:
            - main
        tags:
            - '*'
    pull_request: ~
    workflow_dispatch: ~

jobs:
    split:
        runs-on: ubuntu-latest
        name: Split

        steps:
            -
                uses: actions/checkout@v2
                with:
                    fetch-depth: 0

            -
                name: Split
                uses: "./"
                with:
                    package_path: 'tests/packages/dummy'
                    personal_access_token: ${{ secrets.PAT }}
                    git_username: 'jakubtobiasz'
                    git_email: 'jakub.tobiasz@icloud.com'
                    repository_owner: 'alphpaca'
                    repository_name: 'monoplus-split-demo'
